version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: avito-db
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - avito-db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: avito-pgadmin
    depends_on:
      - db
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5055:80"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito-migrate
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app
    command: ["make", "migrate-up"]
    volumes:
      - .:/app
    restart: "on-failure"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avito-app
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    working_dir: /app
    command: ["./app"]
    ports:
      - "${APP_PORT}:8080"

volumes:
  avito-db-data:
